[build]
  publish = "public" # Thư mục public là nơi Netlify sẽ lấy file chính để host

[[redirects]]
  from = "/admin"
  to = "/admin/view/index.html"
  status = 200

[[redirects]]
  from = "/customer"
  to = "/customer/view/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200